(function(){
  var KEY='billsos-action-log-v1';
  function readLog(){try{var rows=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(rows)?rows:[]}catch(e){return []}}
  function saveLog(rows){localStorage.setItem(KEY,JSON.stringify((rows||[]).slice(0,30)))}
  function addLog(text){var rows=readLog();rows.unshift({time:new Date().toISOString(),text:String(text||'')});saveLog(rows);renderLog()}
  window.BillsOSLogAction=addLog;
  function clean(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
  function fmt(v){return Number(v||0).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0})}
  function val(id){var el=document.getElementById(id);return el?el.value:''}
  function renderLog(){var box=document.getElementById('billsosActionLogRows');if(!box)return;var rows=readLog().slice(0,10);box.innerHTML=rows.length?rows.map(function(row){var d=new Date(row.time);return '<div class="billsosActionRow"><span>'+clean(d.toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}))+'</span><b>'+clean(row.text)+'</b></div>'}).join(''):'<div class="billsosActionEmpty">No recent actions recorded on this device.</div>'}
  function addStyles(){if(document.getElementById('billsosActionCss'))return;var s=document.createElement('style');s.id='billsosActionCss';s.textContent='.billsosActionCard{margin:14px 0}.billsosActionHead{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:8px}.billsosActionHead h2{margin:0;font-size:18px}.billsosActionRow{display:grid;grid-template-columns:120px 1fr;gap:10px;border-top:1px solid rgba(20,35,55,.08);padding:8px 0;font-size:13px}.billsosActionRow:first-child{border-top:0}.billsosActionRow span{color:var(--mut,#556372)}.billsosActionRow b{font-weight:750}.billsosActionEmpty{color:var(--mut,#556372);font-size:13px}.billsosActionClear{border:1px solid var(--line,rgba(20,35,55,.14));border-radius:10px;background:#fff;padding:6px 9px;font-weight:750;color:var(--ink,#14202c)}@media(max-width:700px){.billsosActionRow{grid-template-columns:1fr}}';document.head.appendChild(s)}
  function addPanel(){if(document.getElementById('billsosActionLog')){renderLog();return}var anchor=document.querySelector('.grid');if(!anchor)return;var card=document.createElement('div');card.id='billsosActionLog';card.className='card billsosActionCard';card.innerHTML='<div class="billsosActionHead"><h2>Action summary</h2><button class="billsosActionClear" type="button" id="billsosActionClear">Clear</button></div><div id="billsosActionLogRows"></div>';anchor.parentNode.insertBefore(card,anchor.nextSibling);var clear=document.getElementById('billsosActionClear');if(clear)clear.onclick=function(){saveLog([]);renderLog()};renderLog()}
  function wrap(name,makeText){var original=window[name];if(typeof original!=='function'||original.__actionWrapped)return;var wrapped=function(){var text='';try{text=makeText()}catch(e){}var result=original.apply(this,arguments);if(text)addLog(text);return result};wrapped.__actionWrapped=true;window[name]=wrapped}
  function wrapControl(){wrap('saveOneFromForm',function(){return 'Added one-time item: '+(val('oneName')||'One-time item')+' — '+fmt(val('oneAmount'))});wrap('saveBillFromForm',function(){return 'Added/updated bill: '+(val('billName')||'Bill')+' — '+fmt(val('billAmount'))});wrap('saveIncomeFromForm',function(){return 'Added/updated income: '+(val('incomeName')||'Income')+' — '+fmt(val('incomeAmount'))});wrap('saveBalanceCorrection',function(){return 'Added balance correction: '+(val('balNote')||'Balance correction')+' — '+fmt(val('balAmount'))})}
  document.addEventListener('change',function(e){var cb=e.target;if(!cb||cb.type!=='checkbox'||!cb.dataset||!cb.dataset.id)return;var label=cb.closest('label'),name=label&&label.querySelector('span')?label.querySelector('span').textContent.trim():'item',amt=label&&label.querySelector('b')?' — '+label.querySelector('b').textContent.trim():'';addLog((cb.checked?'Marked completed: ':'Reopened: ')+name+amt)},true);
  document.addEventListener('DOMContentLoaded',function(){addStyles();setTimeout(addPanel,300);setTimeout(addPanel,1200);setTimeout(wrapControl,500);setTimeout(wrapControl,1500)});
})();
