(function(){
'use strict';
var BUILD='balance-chain-20260707-2';
var VERSION='20260707balancechain2';
var MONTHS=['june','july','aug','sep','oct','nov','dec'];
var MONTH_NUMS={june:5,july:6,aug:7,sep:8,oct:9,nov:10,dec:11};
var ONE_TIME_KEYS=['billsos-one-time-bills-v1','billsos-one-time-bills','billsos-manual-bills-v1','billsos-assistant-bills-v1','billsos-payment-log-v1','billsos-activity-log-v1'];
var OVERLAYS=[{name:'Travelers Insurance',startMonth:'july',day:1,amountByMonth:{july:521},defaultAmount:261,flag:'auto'}];
var timer=null,running=false,completed=null,applying=false;
window.BillsOSModules=window.BillsOSModules||{};
window.BillsOSModules.bootstrap={loaded:true,build:BUILD,at:new Date().toISOString(),modules:[]};
function clean(v){return String(v||'').replace(/\s+/g,' ').trim();}
function num(v){var n=Number(String(v||'').replace(/[−–—]/g,'-').replace(/[^0-9.\-]/g,''));return isNaN(n)?null:n;}
function absNum(v){var n=num(v);return n==null?0:Math.abs(n);}
function money(v,d){return v==null||isNaN(v)?'—':'$'+Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});}
function out(v){return '−'+Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});}
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')||f;}catch(e){return f;}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v||{}));}catch(e){}}
function dateOf(v){var m=String(v||'').match(/20\d{2}-\d{2}-\d{2}/);return m?m[0]:'';}
function monthFromIso(iso){return MONTHS[Number(iso.slice(5,7))-6]||'';}
function evId(ev){var day=ev.closest('.day'),panel=ev.closest('.month-panel');return (panel&&panel.id?panel.id.replace('panel-',''):'month')+'|'+(day?day.dataset.day:'x')+'|'+clean((ev.querySelector('.nm')||{}).textContent)+'|'+clean((ev.querySelector('.amt')||{}).textContent);}
function updateProgress(panel){var evs=[].slice.call(panel.querySelectorAll('.ev')).filter(function(ev){return !ev.classList.contains('in')&&!ev.classList.contains('note');});var paid=evs.filter(function(ev){return ev.classList.contains('done');}).length;var pc=panel.querySelector('.paidCount'),pt=panel.querySelector('.paidTotal'),bar=panel.querySelector('.paidBar'),st=panel.querySelector('.saveStatus,.savestatus');if(pc)pc.textContent=paid;if(pt)pt.textContent=evs.length;if(bar)bar.style.width=evs.length?Math.round(paid/evs.length*100)+'%':'0%';if(st){st.textContent='Synced';st.className='saveStatus savestatus ok';}}
function collectCompleted(){var c={};document.querySelectorAll('.month-panel .ev').forEach(function(ev){if(ev.classList.contains('in')||ev.classList.contains('note'))return;var box=ev.querySelector('input[type="checkbox"]');if(box&&box.checked)c[evId(ev)]=1;});return c;}
function applyCompleted(c){if(!c)return;applying=true;document.querySelectorAll('.month-panel .ev').forEach(function(ev){if(ev.classList.contains('in')||ev.classList.contains('note'))return;var box=ev.querySelector('input[type="checkbox"]');if(!box)return;var checked=!!c[evId(ev)];box.checked=checked;ev.classList.toggle('done',checked);});document.querySelectorAll('.month-panel').forEach(updateProgress);applying=false;}
async function loadCompleted(){var local=read('billsos-completed-events-v1',{});try{var r=await fetch('/api/checkmarks',{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error('HTTP '+r.status);var data=await r.json();var remote=data&&data.completed&&typeof data.completed==='object'?data.completed:{};completed=Object.keys(remote).length?remote:local;write('billsos-completed-events-v1',completed);applyCompleted(completed);window.BillsOSModules.checkmarkSync={loaded:true,build:BUILD,at:new Date().toISOString()};}catch(e){completed=local;applyCompleted(local);window.BillsOSModules.checkmarkSync={loaded:false,build:BUILD,error:String(e&&e.message||e),fallback:'localStorage',at:new Date().toISOString()};}}
function bindChecks(){document.addEventListener('change',function(e){var t=e.target;if(applying||!t||!t.matches||!t.matches('.month-panel .ev input[type="checkbox"]'))return;setTimeout(function(){var c=collectCompleted();write('billsos-completed-events-v1',c);completed=c;try{fetch('/api/checkmarks',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({completed:c})});}catch(err){}},0);},true);}
function savedBills(){var list=[];function walk(v){if(!v)return;if(Array.isArray(v)){v.forEach(walk);return;}if(typeof v==='object'){var d=dateOf(v.iso||v.date||v.dueDate||v.due||v.when),a=absNum(v.amount||v.value||v.payment||v.total),n=clean(v.name||v.title||v.bill||v.payee||v.merchant||v.description||v.memo);if(d&&a&&n)list.push({date:d,amount:a,name:n});['items','bills','payments'].forEach(function(k){if(v[k])walk(v[k]);});}}ONE_TIME_KEYS.forEach(function(k){walk(read(k,null));});var seen={};return list.filter(function(x){var id=x.date+'|'+x.amount+'|'+x.name;if(seen[id])return false;seen[id]=1;return true;});}
function ensure(doc,dayNum,name,amount,cls,flag){var day=doc.querySelector('.day[data-day="'+dayNum+'"]');if(!day)return;var events=day.querySelector('.events');if(!events){events=doc.createElement('div');events.className='events';day.insertBefore(events,day.querySelector('.eod')||null);}var id=name+'|'+out(amount);var exists=[].slice.call(events.querySelectorAll('.ev')).some(function(ev){return clean((ev.querySelector('.nm')||{}).textContent)+'|'+clean((ev.querySelector('.amt')||{}).textContent)===id;});if(exists)return;var ev=doc.createElement('div');ev.className='ev '+(cls||'out')+' billsos-balance-extra';ev.innerHTML='<span class="dot"></span><span class="nm"></span><span class="flag '+(flag||'manual')+'">'+((flag||'manual')==='auto'?'A':'M')+'</span><span class="amt"></span>';ev.querySelector('.nm').textContent=name;ev.querySelector('.amt').textContent=out(amount);events.appendChild(ev);}
function enrich(doc,month){OVERLAYS.forEach(function(o){if((MONTH_NUMS[month]+1)<(MONTH_NUMS[o.startMonth]+1))return;ensure(doc,o.day,o.name,o.amountByMonth&&o.amountByMonth[month]!=null?o.amountByMonth[month]:o.defaultAmount,'out',o.flag);});savedBills().forEach(function(b){if(monthFromIso(b.date)!==month)return;ensure(doc,Number(b.date.slice(8,10)),b.name,b.amount,'out','manual');});}
async function getDoc(month){var r=await fetch('/months/'+month+'.html?v='+VERSION,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error(month+' HTTP '+r.status);var doc=new DOMParser().parseFromString(await r.text(),'text/html');enrich(doc,month);return doc;}
function delta(ev){if(ev.classList.contains('note'))return 0;var a=num((ev.querySelector('.amt')||{}).textContent);if(a==null)return 0;a=Math.abs(a);return ev.classList.contains('in')?a:-a;}
function chip(panel,label,value){var k=[].slice.call(panel.querySelectorAll('.chip .k')).find(function(el){return clean(el.textContent).toLowerCase()===label.toLowerCase();});var v=k&&k.closest('.chip')&&k.closest('.chip').querySelector('.v');if(v)v.textContent=value;}
function spark(panel,balances){var svg=panel.querySelector('.sparksvg');if(!svg||!balances.length)return;var vals=balances.map(function(b){return b.balance;}).concat([1000]),min=Math.min.apply(null,vals),max=Math.max.apply(null,vals);if(max===min){max+=1;min-=1;}var padX=26,w=948,padY=26,h=174;function x(i){return padX+(balances.length<=1?0:i/(balances.length-1)*w);}function y(v){return padY+(max-v)/(max-min)*h;}var pts=balances.map(function(b,i){return x(i).toFixed(1)+','+y(b.balance).toFixed(1);}).join(' ');var low=balances.reduce(function(a,b){return b.balance<a.balance?b:a;},balances[0]),high=balances.reduce(function(a,b){return b.balance>a.balance?b:a;},balances[0]);svg.innerHTML='<polyline class="balpath" fill="none" points="'+pts+'"></polyline><circle cx="'+x(high.day-1).toFixed(1)+'" cy="'+y(high.balance).toFixed(1)+'" r="4.5"></circle><text class="mk" text-anchor="middle" x="'+x(high.day-1).toFixed(1)+'" y="'+(y(high.balance)-12).toFixed(1)+'">peak '+money(high.balance,0)+'</text><circle cx="'+x(low.day-1).toFixed(1)+'" cy="'+y(low.balance).toFixed(1)+'" r="4.5"></circle><text class="mk" text-anchor="middle" x="'+x(low.day-1).toFixed(1)+'" y="'+(y(low.balance)+20).toFixed(1)+'">low '+money(low.balance,0)+'</text>';}
function applyMonth(month,doc,opening){var panel=document.getElementById('panel-'+month);if(!panel)return opening;var days=[].slice.call(doc.querySelectorAll('.day[data-day]')).sort(function(a,b){return Number(a.dataset.day)-Number(b.dataset.day);});if(!days.length)return opening;var running=opening;if(running==null){var first=doc.querySelector('.day[data-day] .bod b');running=num(first&&first.textContent);}if(running==null)return opening;var start=running,income=0,outflow=0,sweep=0,balances=[];days.forEach(function(src){var n=Number(src.dataset.day),rendered=panel.querySelector('.day[data-day="'+n+'"]');if(rendered){var bod=rendered.querySelector('.bod b');if(bod)bod.textContent=money(running,2);}var dd=0;src.querySelectorAll('.ev').forEach(function(ev){var d=delta(ev),name=clean((ev.querySelector('.nm')||{}).textContent).toLowerCase();if(d>0)income+=d;if(d<0)outflow+=Math.abs(d);if(d<0&&ev.classList.contains('xfer')&&name.indexOf('sweep')>-1)sweep+=Math.abs(d);dd+=d;});running+=dd;if(rendered){var eod=rendered.querySelector('.eod b');if(eod)eod.textContent=money(running,2);rendered.classList.toggle('is-warn',running<1250);}balances.push({day:n,balance:running});});chip(panel,'Starting',money(start,2));chip(panel,'Opening',money(start,2));chip(panel,'Income',money(income,2));chip(panel,'Money in',money(income,2));chip(panel,'Outflow',money(outflow,2));chip(panel,'Money out',money(outflow,2));if(sweep>0)chip(panel,'Sweep',money(sweep,2));spark(panel,balances);panel.dataset.balanceChained='1';return running;}
async function recalc(){if(running)return;if(!document.getElementById('panel-july')||!document.getElementById('panel-aug'))return;running=true;try{var end=null;for(var i=0;i<MONTHS.length;i++){var m=MONTHS[i];end=applyMonth(m,await getDoc(m),end);}window.BillsOSModules.balanceChain={loaded:true,build:BUILD,at:new Date().toISOString()};}catch(e){window.BillsOSModules.balanceChain={loaded:false,build:BUILD,error:String(e&&e.message||e),at:new Date().toISOString()};}finally{running=false;}}
function schedule(){clearTimeout(timer);timer=setTimeout(recalc,100);}
function loadModule(src,name){var s=document.createElement('script');s.src=src+'?v='+VERSION;s.async=false;s.onload=function(){window.BillsOSModules.bootstrap.modules.push({name:name,loaded:true,at:new Date().toISOString()});};document.head.appendChild(s);}
function init(){bindChecks();loadCompleted();schedule();var target=document.getElementById('month-panels')||document.body;new MutationObserver(function(){if(completed)applyCompleted(completed);schedule();}).observe(target,{childList:true,subtree:true});setInterval(loadCompleted,30000);setInterval(schedule,2500);loadModule('/mobile-ui.js','mobile-ui');loadModule('/dashboard-sync.js','dashboard-sync');loadModule('/assistant-ui.js','assistant-ui');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();