(function(root,factory){
if(typeof module==='object'&&module.exports)module.exports=factory();else root.BillsOSCashflow=factory();
})(typeof self!=='undefined'?self:this,function(){
'use strict';
var YEAR=2026,FLOOR=1000,FIRST_BEGIN=3671,DAY=86400000;
var MONTHS=[['june',6,'June'],['july',7,'July'],['august',8,'August'],['september',9,'September'],['october',10,'October'],['november',11,'November'],['december',12,'December']];
var SHORT={jun:'june',june:'june',jul:'july',july:'july',aug:'august',august:'august',sep:'september',sept:'september',september:'september',oct:'october',october:'october',nov:'november',november:'november',dec:'december',december:'december'};
function norm(x){x=x&&typeof x==='object'?x:{};return{bills:Array.isArray(x.bills)?x.bills:[],income:Array.isArray(x.income)?x.income:[],oneTimeEvents:Array.isArray(x.oneTimeEvents)?x.oneTimeEvents:[],reserves:Array.isArray(x.reserves)?x.reserves:[],updatedAt:x.updatedAt||null};}
function days(m){return new Date(YEAR,m,0).getDate();}
function iso(m,d){return YEAR+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0');}
function monthValue(m){return YEAR+'-'+String(m).padStart(2,'0');}
function monthOffset(m,offset){var d=new Date(YEAR,m-1,1);d.setMonth(d.getMonth()+Number(offset||0));return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
function validIso(v){return /^20[0-9]{2}-[0-9]{2}-[0-9]{2}$/.test(String(v||''));}
function date(v){return new Date(v+'T12:00:00');}
function diff(a,b){return Math.round((date(b)-date(a))/DAY);}
function after(dt,start){return !validIso(start)||dt>=start;}
function skipped(row,dt){return Array.isArray(row&&row.excludedDates)&&row.excludedDates.indexOf(dt)>=0;}
function isCorrection(row){var type=String(row&&row.type||'').toLowerCase(),name=String(row&&row.name||row&&row.label||row&&row.title||'').toLowerCase(),notes=String(row&&row.notes||'').toLowerCase();return type.indexOf('correction')>=0||type.indexOf('adjustment')>=0||name.indexOf('balance correction')>=0||notes.indexOf('manual balance correction')>=0;}
function correctionAmount(row){var raw=Number(row&&((row.amount!=null&&row.amount)||row.value)||0),direction=String(row&&row.correctionDirection||row&&row.direction||'').toLowerCase();if(direction==='subtract'||direction==='decrease'||direction==='negative')return-Math.abs(raw);if(direction==='add'||direction==='increase'||direction==='positive')return Math.abs(raw);return raw;}
function today(){var d=new Date();d.setHours(0,0,0,0);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function addDays(v,n){var d=date(v);d.setDate(d.getDate()+n);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function dollars(n){return n==null||isNaN(n)?'—':'$'+Number(Math.max(0,n)).toLocaleString(undefined,{maximumFractionDigits:0});}
function signed(n){return (n<0?'−':'')+'$'+Math.abs(Number(n||0)).toLocaleString(undefined,{maximumFractionDigits:0});}
function fmt(v){return v?date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'—';}
function monthByName(name){name=SHORT[String(name||'').toLowerCase().replace(/[^a-z]/g,'')];return MONTHS.find(function(x){return x[0]===name;})||null;}
function monthFromIso(v){var m=Number(String(v||'').slice(5,7));return MONTHS.find(function(x){return x[1]===m;})||null;}
function scopeFromQuestion(q){var s=String(q||'').toLowerCase(),now=today(),token=(s.match(/\b(jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t)?(?:ember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)\b/)||[])[1],mm=monthByName(token);if(mm)return{start:iso(mm[1],1),end:iso(mm[1],days(mm[1])),label:mm[2],month:mm[0]};if(/next month/.test(s)){var d=date(now);d.setMonth(d.getMonth()+1);mm=MONTHS.find(function(x){return x[1]===d.getMonth()+1;});if(mm)return{start:iso(mm[1],1),end:iso(mm[1],days(mm[1])),label:mm[2],month:mm[0]};}if(/this month/.test(s)){mm=monthFromIso(now);if(mm)return{start:now,end:iso(mm[1],days(mm[1])),label:mm[2],month:mm[0]};}var m=s.match(/(?:next|within|in)\s+(\d+)\s*(day|days|week|weeks|month|months)/),n=21;if(m)n=Number(m[1])*(m[2].indexOf('week')===0?7:m[2].indexOf('month')===0?30:1);else if(/two weeks|2 weeks/.test(s))n=14;else if(/week/.test(s))n=7;else if(/month/.test(s))n=30;return{start:now,end:addDays(now,n),label:'next '+n+' days'};}
function parseAmount(q){var s=String(q||''),m=s.match(/\$\s*([0-9][0-9,]*(?:\.\d{1,2})?)/)||s.match(/(?:pay|payment|spend|buy|afford|for)\s+([0-9][0-9,]*(?:\.\d{1,2})?)/i);return m?Number(m[1].replace(/,/g,'')):0;}
function oneDates(item,mv){var out=[],explicit=[item&&item.date,item&&item.iso,item&&item.startDate,item&&item.effectiveDate].filter(validIso);if(explicit.length){explicit.forEach(function(d){if(d.slice(0,7)===mv&&!out.includes(d))out.push(d);});return out;}var raw=String(item&&item.notes||'');(raw.match(/20[0-9]{2}-[0-9]{2}-[0-9]{2}/g)||[]).forEach(function(d){if(d.slice(0,7)===mv&&!out.includes(d))out.push(d);});return out;}
function defaultReserves(data){if(data.reserves&&data.reserves.length)return data.reserves;var mortgage=(data.bills||[]).find(function(b){return b&&b.active!==false&&/mortgage/i.test(String(b.name||''))&&/rocket/i.test(String(b.name||''));});if(!mortgage||!Number(mortgage.amount))return[];var half=Math.round(Math.abs(Number(mortgage.amount))*50)/100;return[
{id:'policy-mortgage-reserve-prior-27',name:'Mortgage reserve · first half',amount:half,dueDay:27,frequency:'monthly',active:true,targetBillId:mortgage.id,targetBillName:mortgage.name,targetMonthOffset:1,startMonth:'2026-08',notes:'Reserve from the late-month paycheck for next month’s Rocket payment.'},
{id:'policy-mortgage-reserve-current-13',name:'Mortgage reserve · second half',amount:Math.round((Math.abs(Number(mortgage.amount))-half)*100)/100,dueDay:13,frequency:'monthly',active:true,targetBillId:mortgage.id,targetBillName:mortgage.name,targetMonthOffset:0,startMonth:'2026-09',notes:'Reserve from the mid-month paycheck before the Rocket payment on the 15th.'}
];}
function addIncome(row,m,dim,push){if(row.active===false)return;var amount=Math.abs(Number(row.amount||0)),name=row.name||'Income',schedule=row.schedule||'manual',start=row.startDate||row.start||row.anchorDate||'';if(!amount)return;function pushIf(day){var dt=iso(m,day);if(after(dt,start)&&!skipped(row,dt))push({day:day,name:name,amount:amount,cls:'in',type:'income',sourceId:row.id||''});}if(schedule==='semi-monthly-15-30'){pushIf(15);pushIf(Math.min(30,dim));return;}if(schedule==='biweekly'){if(validIso(start)){for(var day=1;day<=dim;day++){var dt=iso(m,day),gap=diff(start,dt);if(gap>=0&&gap%14===0&&!skipped(row,dt))push({day:day,name:name,amount:amount,cls:'in',type:'income',sourceId:row.id||''});}}else{[1,15,29].forEach(function(day){if(day<=dim)pushIf(day);});}return;}if(schedule==='monthly'){pushIf(validIso(start)?Math.min(Number(start.slice(8,10)),dim):1);return;}if(validIso(start)&&start.slice(0,7)===YEAR+'-'+String(m).padStart(2,'0')&&!skipped(row,start))push({day:Number(start.slice(8,10)),name:name,amount:amount,cls:'in',type:'income',sourceId:row.id||''});}
function rowsForMonth(raw,m,begin){var data=norm(raw),mv=monthValue(m),dim=days(m),rows=[];function push(input){var day=Number(input&&input.day||0),amount=Number(input&&input.amount||0);if(day>=1&&day<=dim&&Number.isFinite(amount))rows.push({iso:iso(m,day),day:day,name:input.name||'Item',amount:amount,availableAmount:amount,cls:input.cls||'out',type:input.type||'',sourceId:input.sourceId||'',reserveAmount:Number(input.reserveAmount||0),reserveTargetKey:input.reserveTargetKey||'',reserveTargetName:input.reserveTargetName||'',notes:input.notes||''});}
data.bills.forEach(function(b){if(b.active===false)return;var f=b.frequency||'monthly';if(f!=='monthly'||b.startMonth&&b.startMonth>mv||b.endMonth&&b.endMonth<mv)return;var day=Math.min(Number(b.dueDay||1),dim),dt=iso(m,day);if(skipped(b,dt))return;push({day:day,name:b.name||'Bill',amount:-Math.abs(Number(b.amount||0)),cls:'out',type:b.payMethod||b.paymentMethod||b.type,sourceId:b.id||''});});
data.oneTimeEvents.forEach(function(o){if(!o||/^__billsos_/.test(String(o.id||'')))return;oneDates(o,mv).forEach(function(dt){var rawAmount=Number(o.amount!=null?o.amount:o.value||0),type=String(o.type||'').toLowerCase(),name=String(o.name||o.label||o.title||'One-time item'),correction=isCorrection(o),income=type==='income',amount=correction?correctionAmount(o):(income?Math.abs(rawAmount):-Math.abs(rawAmount));push({day:Number(dt.slice(8,10)),name:name,amount:amount,cls:amount>=0?'in':'out',type:correction?'balance-correction':o.type,sourceId:o.id||'',notes:o.notes||''});});});
defaultReserves(data).forEach(function(r){if(!r||r.active===false)return;if((r.frequency||'monthly')!=='monthly'||r.startMonth&&r.startMonth>mv||r.endMonth&&r.endMonth<mv)return;var day=Math.min(Number(r.dueDay||1),dim),targetMonth=monthOffset(m,Number(r.targetMonthOffset||0)),targetKey=String(r.targetBillId||r.targetBillName||'mortgage')+'@'+targetMonth;push({day:day,name:r.name||'Reserve',amount:0,cls:'reserve',type:'reserve',sourceId:r.id||'',reserveAmount:Math.abs(Number(r.amount||0)),reserveTargetKey:targetKey,reserveTargetName:r.targetBillName||'',notes:r.notes||''});});
data.income.forEach(function(i){addIncome(i,m,dim,push);});return rows.sort(function(a,b){return a.iso.localeCompare(b.iso)||((a.type==='reserve')?-1:0)-((b.type==='reserve')?-1:0)||b.amount-a.amount;});}
function totalReserved(map){return Object.keys(map).reduce(function(sum,key){return sum+Math.max(0,Number(map[key]||0));},0);}
function build(raw,opt){var data=norm(raw),opts=opt||{},floorNegative=opts.floorNegative!==false,balances=[],events=[],months={},bal=Number(opts.firstBegin==null?FIRST_BEGIN:opts.firstBegin),availableBal=bal,reservedByTarget={};MONTHS.forEach(function(mm){var begin=bal,availableBegin=availableBal,rows=rowsForMonth(data,mm[1],begin),run=begin,availableRun=availableBegin;rows.forEach(function(r){if(r.type==='reserve'&&r.reserveAmount>0){reservedByTarget[r.reserveTargetKey]=(reservedByTarget[r.reserveTargetKey]||0)+r.reserveAmount;r.availableAmount=-r.reserveAmount;}else if(r.sourceId){var paymentKey=String(r.sourceId)+'@'+monthValue(mm[1]),held=Math.max(0,Number(reservedByTarget[paymentKey]||0));if(r.amount<0&&held>0){var release=Math.min(Math.abs(r.amount),held);reservedByTarget[paymentKey]=Math.max(0,held-release);r.reserveRelease=release;r.availableAmount=r.amount+release;}}events.push({iso:r.iso,name:r.name,amount:r.amount,availableAmount:r.availableAmount,reserveAmount:r.reserveAmount||0,reserveRelease:r.reserveRelease||0,reserveTargetName:r.reserveTargetName||'',amountText:dollars(Math.abs(r.type==='reserve'?r.reserveAmount:r.amount)),cls:r.cls,type:r.type,done:false});});for(var day=1;day<=days(mm[1]);day++){rows.filter(function(r){return r.day===day;}).forEach(function(r){run+=r.amount;availableRun+=Number(r.availableAmount==null?r.amount:r.availableAmount);});if(floorNegative&&run<0)run=0;if(floorNegative&&availableRun<0)availableRun=0;balances.push({iso:iso(mm[1],day),balance:run,availableBalance:availableRun,reserved:totalReserved(reservedByTarget)});}months[mm[0]]={name:mm[2],number:mm[1],begin:begin,end:run,availableBegin:availableBegin,availableEnd:availableRun,reservedEnd:totalReserved(reservedByTarget),rows:rows};bal=run;availableBal=availableRun;});return{balances:balances,events:events,months:months,reserves:defaultReserves(data),updatedAt:data.updatedAt||null};}
function inScope(model,scope){return{balances:(model&&model.balances||[]).filter(function(x){return x.iso>=scope.start&&x.iso<=scope.end;}),events:(model&&model.events||[]).filter(function(x){return x.iso>=scope.start&&x.iso<=scope.end;})};}
function isIncome(e){return e.amount>0||/\bin\b/.test(' '+(e.cls||'')+' ');}
function openEvents(model,scope){return inScope(model,scope).events.filter(function(e){return !/\bnote\b/.test(' '+(e.cls||'')+' ')&&!e.done;});}
function lowBalance(model,scope){return inScope(model,scope).balances.reduce(function(a,b){var av=b.availableBalance==null?b.balance:b.availableBalance,aa=a&&(a.availableBalance==null?a.balance:a.availableBalance);return !a||av<aa?b:a;},null);}
function bestPaymentDay(model,amount,scope,options){var floor=Number((options&&options.floor)||FLOOR),ev=openEvents(model,scope),ds=inScope(model,scope).balances;if(!ds.length)return null;return ds.map(function(d){var base=d.availableBalance==null?d.balance:d.availableBalance,near=ev.filter(function(e){var gap=Math.round((date(e.iso)-date(d.iso))/DAY);return !isIncome(e)&&Math.abs(e.amount)>=300&&Math.abs(gap)<=3;}),same=ev.filter(function(e){return e.iso===d.iso&&!isIncome(e);}),after=Math.max(0,base-amount),buffer=after-floor,hasRecentIncome=ev.some(function(e){var gap=Math.round((date(d.iso)-date(e.iso))/DAY);return isIncome(e)&&gap>=0&&gap<=3;}),wknd=[0,6].indexOf(date(d.iso).getDay())>-1,score=buffer+(hasRecentIncome?225:0)-near.length*175-same.length*90-(wknd?40:0);return{iso:d.iso,balance:d.balance,availableBalance:base,after:after,buffer:buffer,near:near,score:score};}).sort(function(a,b){return b.score-a.score;})[0];}
return{BUILD:'cashflow-engine-20260818-reserves1',YEAR:YEAR,FLOOR:FLOOR,FIRST_BEGIN:FIRST_BEGIN,MONTHS:MONTHS,norm:norm,build:build,rowsForMonth:rowsForMonth,defaultReserves:defaultReserves,scopeFromQuestion:scopeFromQuestion,parseAmount:parseAmount,inScope:inScope,openEvents:openEvents,lowBalance:lowBalance,bestPaymentDay:bestPaymentDay,isIncome:isIncome,isCorrection:isCorrection,correctionAmount:correctionAmount,dollars:dollars,signed:signed,fmt:fmt,addDays:addDays,today:today};
});
