(function(root,factory){
if(typeof module==='object'&&module.exports)module.exports=factory();else root.BillsOSCashflow=factory();
})(typeof self!=='undefined'?self:this,function(){
'use strict';
var YEAR=2026,FLOOR=1000,FIRST_BEGIN=0,DAY=86400000;
var MONTHS=[['june',6,'June',2026],['july',7,'July',2026],['august',8,'August',2026],['september',9,'September',2026],['october',10,'October',2026],['november',11,'November',2026],['december',12,'December',2026],['january-2027',1,'January',2027],['february-2027',2,'February',2027],['march-2027',3,'March',2027]];
var SHORT={jan:'january-2027',january:'january-2027',feb:'february-2027',february:'february-2027',mar:'march-2027',march:'march-2027',jun:'june',june:'june',jul:'july',july:'july',aug:'august',august:'august',sep:'september',sept:'september',september:'september',oct:'october',october:'october',nov:'november',november:'november',dec:'december',december:'december'};
function norm(x){x=x&&typeof x==='object'?x:{};return{bills:Array.isArray(x.bills)?x.bills:[],income:Array.isArray(x.income)?x.income:[],oneTimeEvents:Array.isArray(x.oneTimeEvents)?x.oneTimeEvents:[],paymentSplits:Array.isArray(x.paymentSplits)?x.paymentSplits:[],updatedAt:x.updatedAt||null};}
function periodYear(m,y){if(Number.isInteger(Number(y)))return Number(y);var found=MONTHS.find(function(x){return x[1]===Number(m);});return found?found[3]:YEAR;}
function days(m,y){return new Date(periodYear(m,y),m,0).getDate();}
function iso(m,d,y){return periodYear(m,y)+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0');}
function monthValue(m,y){return periodYear(m,y)+'-'+String(m).padStart(2,'0');}
function monthOffset(m,offset){var d=new Date(YEAR,m-1,1);d.setMonth(d.getMonth()+Number(offset||0));return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
function monthShort(v){var p=String(v||'').split('-').map(Number);return new Date(p[0],p[1]-1,1).toLocaleString(undefined,{month:'short'});}
function validIso(v){return /^20[0-9]{2}-[0-9]{2}-[0-9]{2}$/.test(String(v||''));}
function date(v){return new Date(v+'T12:00:00');}
function diff(a,b){return Math.round((date(b)-date(a))/DAY);}
function after(dt,start){return !validIso(start)||dt>=start;}
function skipped(row,dt){return Array.isArray(row&&row.excludedDates)&&row.excludedDates.indexOf(dt)>=0;}
function isCorrection(row){var type=String(row&&row.type||'').toLowerCase(),name=String(row&&row.name||row&&row.label||row&&row.title||'').toLowerCase(),notes=String(row&&row.notes||'').toLowerCase();return type.indexOf('correction')>=0||type.indexOf('adjustment')>=0||name.indexOf('balance correction')>=0||notes.indexOf('manual balance correction')>=0;}
function transferKind(row){var name=String(row&&row.name||row&&row.label||row&&row.title||'').toLowerCase(),type=String(row&&row.type||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(/\bsweep\b/.test(name)||type==='sweep')return'sweep';if(/\bfund(?:ing)?\b.*\b(?:spending|account)\b|\b(?:spending|account)\b.*\bfund(?:ing)?\b|\bfunding transfer\b|\btransfer funding\b/.test(name)||/^(?:fund|funding|fund-transfer|funding-transfer|transfer-fund|transfer-funding|spending-funding|account-funding)$/.test(type))return'funding';if(type==='transfer'||/\btransfer\b/.test(name))return'xfer';return'';}
function calendarClass(row){return Number(row&&row.amount||0)>0?'in':(transferKind(row)||'out');}
function correctionAmount(row){var raw=Number(row&&((row.amount!=null&&row.amount)||row.value)||0),direction=String(row&&row.correctionDirection||row&&row.direction||'').toLowerCase();if(direction==='subtract'||direction==='decrease'||direction==='negative')return-Math.abs(raw);if(direction==='add'||direction==='increase'||direction==='positive')return Math.abs(raw);return raw;}
function requestedBalance(row){var match=String(row&&row.notes||'').match(/Requested balance\s+(-?\$[0-9,]+(?:\.[0-9]{1,2})?)/i);if(!match)return null;var value=Number(match[1].replace(/[$,]/g,''));return Number.isFinite(value)?value:null;}
function today(){var d=new Date();d.setHours(0,0,0,0);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function addDays(v,n){var d=date(v);d.setDate(d.getDate()+n);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function dollars(n){return n==null||isNaN(n)?'—':'$'+Number(Math.max(0,n)).toLocaleString(undefined,{maximumFractionDigits:0});}
function signed(n){return (n<0?'−':'')+'$'+Math.abs(Number(n||0)).toLocaleString(undefined,{maximumFractionDigits:0});}
function fmt(v){return v?date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'—';}
function monthByName(name){name=SHORT[String(name||'').toLowerCase().replace(/[^a-z]/g,'')];return MONTHS.find(function(x){return x[0]===name;})||null;}
function monthFromIso(v){var y=Number(String(v||'').slice(0,4)),m=Number(String(v||'').slice(5,7));return MONTHS.find(function(x){return x[1]===m&&x[3]===y;})||null;}
function scopeFromQuestion(q){var s=String(q||'').toLowerCase(),now=today();if(/\bq1(?:\s+2027)?\b|first quarter(?:\s+of\s+2027)?/.test(s))return{start:'2027-01-01',end:'2027-03-31',label:'Q1 2027'};var token=(s.match(/\b(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t)?(?:ember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)\b/)||[])[1],mm=monthByName(token);if(mm)return{start:iso(mm[1],1,mm[3]),end:iso(mm[1],days(mm[1],mm[3]),mm[3]),label:mm[2]+' '+mm[3],month:mm[0]};if(/next month/.test(s)){var d=date(now);d.setMonth(d.getMonth()+1);mm=MONTHS.find(function(x){return x[1]===d.getMonth()+1&&x[3]===d.getFullYear();});if(mm)return{start:iso(mm[1],1,mm[3]),end:iso(mm[1],days(mm[1],mm[3]),mm[3]),label:mm[2]+' '+mm[3],month:mm[0]};}if(/this month/.test(s)){mm=monthFromIso(now);if(mm)return{start:now,end:iso(mm[1],days(mm[1],mm[3]),mm[3]),label:mm[2]+' '+mm[3],month:mm[0]};}var m=s.match(/(?:next|within|in)\s+(\d+)\s*(day|days|week|weeks|month|months)/),n=21;if(m)n=Number(m[1])*(m[2].indexOf('week')===0?7:m[2].indexOf('month')===0?30:1);else if(/two weeks|2 weeks/.test(s))n=14;else if(/week/.test(s))n=7;else if(/month/.test(s))n=30;return{start:now,end:addDays(now,n),label:'next '+n+' days'};}
function parseAmount(q){var s=String(q||''),m=s.match(/\$\s*([0-9][0-9,]*(?:\.\d{1,2})?)/)||s.match(/(?:pay|payment|spend|buy|afford|for)\s+([0-9][0-9,]*(?:\.\d{1,2})?)/i);return m?Number(m[1].replace(/,/g,'')):0;}
function oneDates(item,mv){var out=[],explicit=[item&&item.date,item&&item.iso,item&&item.startDate,item&&item.effectiveDate].filter(validIso);explicit.forEach(function(d){if(d.slice(0,7)===mv&&!out.includes(d))out.push(d);});return out;}
function addIncome(row,m,dim,push,y){if(row.active===false)return;var amount=Math.abs(Number(row.amount||0)),name=row.name||'Income',schedule=row.schedule||'manual',start=row.startDate||row.start||row.anchorDate||'';if(!amount)return;function pushIf(day){var dt=iso(m,day,y);if(after(dt,start)&&!skipped(row,dt))push({day:day,name:name,amount:amount,cls:'in',type:'income',sourceId:row.id||''});}if(schedule==='semi-monthly-15-30'){pushIf(15);pushIf(Math.min(30,dim));return;}if(schedule==='biweekly'){if(validIso(start)){for(var day=1;day<=dim;day++){var dt=iso(m,day,y),gap=diff(start,dt);if(gap>=0&&gap%14===0&&!skipped(row,dt))push({day:day,name:name,amount:amount,cls:'in',type:'income',sourceId:row.id||''});}}return;}if(schedule==='monthly'){if(validIso(start))pushIf(Math.min(Number(start.slice(8,10)),dim));return;}if(validIso(start)&&start.slice(0,7)===monthValue(m,y)&&!skipped(row,start))push({day:Number(start.slice(8,10)),name:name,amount:amount,cls:'in',type:'income',sourceId:row.id||''});}
function rowsForMonth(raw,m,begin,y){var year=periodYear(m,y),data=norm(raw),mv=monthValue(m,year),dim=days(m,year),rows=[];function push(input){var day=Number(input&&input.day||0),amount=Number(input&&input.amount||0);if(day>=1&&day<=dim&&Number.isFinite(amount))rows.push({iso:iso(m,day,year),day:day,name:input.name||'Item',amount:amount,cls:input.cls||'out',type:input.type||'',sourceId:input.sourceId||'',targetMonth:input.targetMonth||'',paymentPart:Number(input.paymentPart||0),paymentParts:Number(input.paymentParts||0),requestedBalance:input.requestedBalance==null?null:Number(input.requestedBalance),notes:input.notes||''});}
data.bills.forEach(function(b){if(b.active===false)return;var f=b.frequency||'monthly',dueDay=Number(b.dueDay);if(f!=='monthly'||!Number.isInteger(dueDay)||dueDay<1||b.startMonth&&b.startMonth>mv||b.endMonth&&b.endMonth<mv)return;var day=Math.min(dueDay,dim),dt=iso(m,day,year);if(skipped(b,dt))return;push({day:day,name:b.name||'Bill',amount:-Math.abs(Number(b.amount||0)),cls:'out',type:b.payMethod||b.paymentMethod||b.type,sourceId:b.id||''});});
data.oneTimeEvents.forEach(function(o){if(!o||/^__billsos_/.test(String(o.id||'')))return;oneDates(o,mv).forEach(function(dt){var rawAmount=Number(o.amount!=null?o.amount:o.value||0),type=String(o.type||'').toLowerCase(),name=String(o.name||o.label||o.title||'One-time item'),correction=isCorrection(o),income=type==='income',amount=correction?correctionAmount(o):(income?Math.abs(rawAmount):-Math.abs(rawAmount));push({day:Number(dt.slice(8,10)),name:name,amount:amount,cls:amount>=0?'in':'out',type:type==='balance-opening-adjustment'?'balance-opening-adjustment':(correction?'balance-correction':o.type),sourceId:o.id||'',requestedBalance:type==='balance-opening-adjustment'?requestedBalance(o):null,notes:o.notes||''});});});
data.income.forEach(function(i){addIncome(i,m,dim,push,year);});return rows.sort(function(a,b){return a.iso.localeCompare(b.iso)||b.amount-a.amount;});}
function build(raw,opt){var data=norm(raw),opts=opt||{},balances=[],events=[],months={},bal=Number(opts.firstBegin==null?FIRST_BEGIN:opts.firstBegin);MONTHS.forEach(function(mm){var year=mm[3]||YEAR,begin=bal,rows=rowsForMonth(data,mm[1],begin,year),run=begin;rows.forEach(function(r){events.push({iso:r.iso,name:r.name,amount:r.amount,amountText:dollars(Math.abs(r.amount)),cls:r.cls,type:r.type,targetMonth:r.targetMonth||'',paymentPart:r.paymentPart||0,paymentParts:r.paymentParts||0,done:false});});for(var day=1;day<=days(mm[1],year);day++){var dayRows=rows.filter(function(r){return r.day===day;}),opening=dayRows.filter(function(r){return r.type==='balance-opening-adjustment';}),regular=dayRows.filter(function(r){return r.type!=='balance-opening-adjustment';});opening.forEach(function(r){run=r.requestedBalance==null?run+r.amount:r.requestedBalance;});var dayBegin=run;regular.forEach(function(r){run+=r.amount;});balances.push({iso:iso(mm[1],day,year),beginning:dayBegin,balance:run});}months[mm[0]]={name:mm[2],number:mm[1],year:year,begin:begin,end:run,rows:rows};bal=run;});return{balances:balances,events:events,months:months,paymentSplits:[],updatedAt:data.updatedAt||null};}
function inScope(model,scope){return{balances:(model&&model.balances||[]).filter(function(x){return x.iso>=scope.start&&x.iso<=scope.end;}),events:(model&&model.events||[]).filter(function(x){return x.iso>=scope.start&&x.iso<=scope.end;})};}
function isIncome(e){return e.amount>0||/\bin\b/.test(' '+(e.cls||'')+' ');}
function openEvents(model,scope){return inScope(model,scope).events.filter(function(e){return !/\bnote\b/.test(' '+(e.cls||'')+' ')&&!e.done;});}
function lowBalance(model,scope){return inScope(model,scope).balances.reduce(function(a,b){return !a||b.balance<a.balance?b:a;},null);}
function bestPaymentDay(model,amount,scope,options){var floor=Number((options&&options.floor)||FLOOR),ev=openEvents(model,scope),ds=inScope(model,scope).balances;if(!ds.length)return null;return ds.map(function(d){var near=ev.filter(function(e){var gap=Math.round((date(e.iso)-date(d.iso))/DAY);return !isIncome(e)&&Math.abs(e.amount)>=300&&Math.abs(gap)<=3;}),same=ev.filter(function(e){return e.iso===d.iso&&!isIncome(e);}),after=Math.max(0,d.balance-amount),buffer=after-floor,hasRecentIncome=ev.some(function(e){var gap=Math.round((date(d.iso)-date(e.iso))/DAY);return isIncome(e)&&gap>=0&&gap<=3;}),wknd=[0,6].indexOf(date(d.iso).getDay())>-1,score=buffer+(hasRecentIncome?225:0)-near.length*175-same.length*90-(wknd?40:0);return{iso:d.iso,balance:d.balance,after:after,buffer:buffer,near:near,score:score};}).sort(function(a,b){return b.score-a.score;})[0];}
return{BUILD:'cashflow-engine-20260826-q12027-1',YEAR:YEAR,FLOOR:FLOOR,FIRST_BEGIN:FIRST_BEGIN,MONTHS:MONTHS,norm:norm,build:build,rowsForMonth:rowsForMonth,scopeFromQuestion:scopeFromQuestion,parseAmount:parseAmount,inScope:inScope,openEvents:openEvents,lowBalance:lowBalance,bestPaymentDay:bestPaymentDay,isIncome:isIncome,isCorrection:isCorrection,correctionAmount:correctionAmount,transferKind:transferKind,calendarClass:calendarClass,dollars:dollars,signed:signed,fmt:fmt,addDays:addDays,today:today};
});
