(function(root,factory){
if(typeof module==='object'&&module.exports)module.exports=factory();else root.BillsOSCashflow=factory();
})(typeof self!=='undefined'?self:this,function(){
'use strict';
var YEAR=2026,FLOOR=1000,FIRST_BEGIN=3671,DAY=86400000;
var MONTHS=[['june',6,'June'],['july',7,'July'],['august',8,'August'],['september',9,'September'],['october',10,'October'],['november',11,'November'],['december',12,'December']];
var SHORT={jun:'june',june:'june',jul:'july',july:'july',aug:'august',august:'august',sep:'september',sept:'september',september:'september',oct:'october',october:'october',nov:'november',november:'november',dec:'december',december:'december'};
function norm(x){x=x&&typeof x==='object'?x:{};return{bills:Array.isArray(x.bills)?x.bills:[],income:Array.isArray(x.income)?x.income:[],oneTimeEvents:Array.isArray(x.oneTimeEvents)?x.oneTimeEvents:[],updatedAt:x.updatedAt||null};}
function days(m){return new Date(YEAR,m,0).getDate();}
function iso(m,d){return YEAR+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0');}
function validIso(v){return /^20[0-9]{2}-[0-9]{2}-[0-9]{2}$/.test(String(v||''));}
function date(v){return new Date(v+'T12:00:00');}
function diff(a,b){return Math.round((date(b)-date(a))/DAY);}
function after(dt,start){return !validIso(start)||dt>=start;}
function today(){var d=new Date();d.setHours(0,0,0,0);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function addDays(v,n){var d=date(v);d.setDate(d.getDate()+n);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function dollars(n){return n==null||isNaN(n)?'—':'$'+Number(Math.max(0,n)).toLocaleString(undefined,{maximumFractionDigits:0});}
function signed(n){return (n<0?'−':'')+'$'+Math.abs(Number(n||0)).toLocaleString(undefined,{maximumFractionDigits:0});}
function fmt(v){return v?date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'—';}
function monthByName(name){name=SHORT[String(name||'').toLowerCase().replace(/[^a-z]/g,'')];return MONTHS.find(function(x){return x[0]===name;})||null;}
function monthFromIso(v){var m=Number(String(v||'').slice(5,7));return MONTHS.find(function(x){return x[1]===m;})||null;}
function scopeFromQuestion(q){var s=String(q||'').toLowerCase(),now=today(),token=(s.match(/\b(jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t)?(?:ember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)\b/)||[])[1],mm=monthByName(token);if(mm)return{start:iso(mm[1],1),end:iso(mm[1],days(mm[1])),label:mm[2],month:mm[0]};if(/next month/.test(s)){var d=date(now);d.setMonth(d.getMonth()+1);mm=MONTHS.find(function(x){return x[1]===d.getMonth()+1;});if(mm)return{start:iso(mm[1],1),end:iso(mm[1],days(mm[1])),label:mm[2],month:mm[0]};}if(/this month/.test(s)){mm=monthFromIso(now);if(mm)return{start:now,end:iso(mm[1],days(mm[1])),label:mm[2],month:mm[0]};}var m=s.match(/(?:next|within|in)\s+(\d+)\s*(day|days|week|weeks|month|months)/),n=21;if(m)n=Number(m[1])*(m[2].indexOf('week')===0?7:m[2].indexOf('month')===0?30:1);else if(/two weeks|2 weeks/.test(s))n=14;else if(/week/.test(s))n=7;else if(/month/.test(s))n=30;return{start:now,end:addDays(now,n),label:'next '+n+' days'};}
function parseAmount(q){var s=String(q||''),m=s.match(/\$\s*([0-9][0-9,]*(?:\.\d{1,2})?)/)||s.match(/(?:pay|payment|spend|buy|afford|for)\s+([0-9][0-9,]*(?:\.\d{1,2})?)/i);return m?Number(m[1].replace(/,/g,'')):0;}
function oneDates(item,mv){var out=[],raw=String(item.notes||'')+' '+String(item.date||'')+' '+String(item.iso||'')+' '+String(item.startDate||'')+' '+String(item.effectiveDate||'');(raw.match(/20[0-9]{2}-[0-9]{2}-[0-9]{2}/g)||[]).forEach(function(d){if(d.slice(0,7)===mv&&!out.includes(d))out.push(d);});return out;}
function addIncome(row,m,dim,push){if(row.active===false)return;var amount=Math.abs(Number(row.amount||0)),name=row.name||'Income',schedule=row.schedule||'manual',start=row.startDate||row.start||row.anchorDate||'';if(!amount)return;function pushIf(day){var dt=iso(m,day);if(after(dt,start))push(day,name,amount,'in','income');}if(schedule==='semi-monthly-15-30'){pushIf(15);pushIf(Math.min(30,dim));return;}if(schedule==='biweekly'){if(validIso(start)){for(var day=1;day<=dim;day++){var dt=iso(m,day),gap=diff(start,dt);if(gap>=0&&gap%14===0)push(day,name,amount,'in','income');}}else{[1,15,29].forEach(function(day){if(day<=dim)push(day,name,amount,'in','income');});}return;}if(schedule==='monthly'){pushIf(validIso(start)?Math.min(Number(start.slice(8,10)),dim):1);return;}if(validIso(start)&&start.slice(0,7)===YEAR+'-'+String(m).padStart(2,'0'))push(Number(start.slice(8,10)),name,amount,'in','income');}
function rowsForMonth(raw,m,begin){var data=norm(raw),mv=YEAR+'-'+String(m).padStart(2,'0'),dim=days(m),rows=[];function push(day,name,amount,cls,type){day=Number(day||0);if(day>=1&&day<=dim)rows.push({iso:iso(m,day),day:day,name:name||'Item',amount:Number(amount||0),cls:cls||'out',type:type||''});}data.bills.forEach(function(b){if(b.active===false)return;var f=b.frequency||'monthly';if(f!=='monthly'||b.startMonth&&b.startMonth>mv||b.endMonth&&b.endMonth<mv)return;push(Math.min(Number(b.dueDay||1),dim),b.name||'Bill',-Math.abs(Number(b.amount||0)),'out',b.payMethod||b.paymentMethod||b.type);});data.oneTimeEvents.forEach(function(o){if(!o||/^__billsos_/.test(String(o.id||'')))return;oneDates(o,mv).forEach(function(dt){var raw=Number(o.amount||o.value||0),type=String(o.type||'').toLowerCase(),name=String(o.name||o.label||o.title||'One-time item'),correction=type.indexOf('correction')>=0||type.indexOf('adjustment')>=0||/correction|adjustment/i.test(name),income=o.type==='income',amount=correction?raw:(income?Math.abs(raw):-Math.abs(raw));push(Number(dt.slice(8,10)),name,amount,amount>=0?'in':'out',o.type);});});data.income.forEach(function(i){addIncome(i,m,dim,push);});return rows.sort(function(a,b){return a.iso.localeCompare(b.iso)||b.amount-a.amount;});}
function build(raw,opt){var data=norm(raw),opts=opt||{},floorNegative=opts.floorNegative!==false,balances=[],events=[],months={},bal=Number(opts.firstBegin==null?FIRST_BEGIN:opts.firstBegin);MONTHS.forEach(function(mm){var begin=bal,rows=rowsForMonth(data,mm[1],begin),run=begin;rows.forEach(function(r){events.push({iso:r.iso,name:r.name,amount:r.amount,amountText:dollars(Math.abs(r.amount)),cls:r.cls,type:r.type,done:false});});for(var day=1;day<=days(mm[1]);day++){rows.filter(function(r){return r.day===day;}).forEach(function(r){run+=r.amount;});if(floorNegative&&run<0)run=0;balances.push({iso:iso(mm[1],day),balance:run});}months[mm[0]]={name:mm[2],number:mm[1],begin:begin,end:run,rows:rows};bal=run;});return{balances:balances,events:events,months:months,updatedAt:data.updatedAt||null};}
function inScope(model,scope){return{balances:(model&&model.balances||[]).filter(function(x){return x.iso>=scope.start&&x.iso<=scope.end;}),events:(model&&model.events||[]).filter(function(x){return x.iso>=scope.start&&x.iso<=scope.end;})};}
function isIncome(e){return e.amount>0||/\bin\b/.test(' '+(e.cls||'')+' ');}
function openEvents(model,scope){return inScope(model,scope).events.filter(function(e){return !/\bnote\b/.test(' '+(e.cls||'')+' ')&&!e.done;});}
function lowBalance(model,scope){return inScope(model,scope).balances.reduce(function(a,b){return !a||b.balance<a.balance?b:a;},null);}
function bestPaymentDay(model,amount,scope,options){var floor=Number((options&&options.floor)||FLOOR),ev=openEvents(model,scope),ds=inScope(model,scope).balances;if(!ds.length)return null;return ds.map(function(d){var near=ev.filter(function(e){var diff=Math.round((date(e.iso)-date(d.iso))/DAY);return !isIncome(e)&&Math.abs(e.amount)>=300&&Math.abs(diff)<=3;}),same=ev.filter(function(e){return e.iso===d.iso&&!isIncome(e);}),after=Math.max(0,d.balance-amount),buffer=after-floor,hasRecentIncome=ev.some(function(e){var gap=Math.round((date(d.iso)-date(e.iso))/DAY);return isIncome(e)&&gap>=0&&gap<=3;}),wknd=[0,6].indexOf(date(d.iso).getDay())>-1,score=buffer+(hasRecentIncome?225:0)-near.length*175-same.length*90-(wknd?40:0);return{iso:d.iso,balance:d.balance,after:after,buffer:buffer,near:near,score:score};}).sort(function(a,b){return b.score-a.score;})[0];}
return{BUILD:'cashflow-engine-20260707-corrections',YEAR:YEAR,FLOOR:FLOOR,FIRST_BEGIN:FIRST_BEGIN,MONTHS:MONTHS,norm:norm,build:build,rowsForMonth:rowsForMonth,scopeFromQuestion:scopeFromQuestion,parseAmount:parseAmount,inScope:inScope,openEvents:openEvents,lowBalance:lowBalance,bestPaymentDay:bestPaymentDay,isIncome:isIncome,dollars:dollars,signed:signed,fmt:fmt,addDays:addDays,today:today};
});