(function(){
  var YEAR=2026;
  var RULE_ID='__billsos_system_rules__';
  function esc(s){return String(s||'').replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
  function money(v){var n=Number(v||0);return n?n.toLocaleString(undefined,{style:'currency',currency:'USD'}):'$0.00'}
  function monthNum(slug){return {june:6,july:7,aug:8,sep:9,oct:10,nov:11,dec:12}[slug]||1;}
  function monthName(slug){return slug.charAt(0).toUpperCase()+slug.slice(1);}
  function daysInMonth(y,m){return new Date(y,m,0).getDate();}
  function dateKey(slug,day){return YEAR+'-'+String(monthNum(slug)).padStart(2,'0')+'-'+String(day).padStart(2,'0')}
  function parseAmount(s){s=String(s||'').replace(/[,$\s]/g,'').replace(/[−–—]/g,'-');return Number(s)||0;}
  function cleanName(s){return String(s||'').replace(/\s+/g,' ').replace(/\s*✓\s*$/,'').trim();}
  function normName(s){return cleanName(s).toLowerCase().replace(/\*/g,'').replace(/—.*/,'').replace(/-.*/,'').replace(/\bacct\b/g,'account').replace(/\s+/g,' ').trim();}
  function normKey(row){return row.date+'|'+normName(row.name);}
  function cents(v){return Math.round(Math.abs(Number(v||0))*100);}
  function sameAmount(a,b){return cents(a.amount)===cents(b.amount);}
  function tokenSet(s){var stop={the:1,and:1,auto:1,manual:1,payment:1,acct:1,account:1,bill:1};var out={};normName(s).split(/[^a-z0-9]+/).forEach(function(t){if(t&&!stop[t])out[t]=1;});return out;}
  function nameScore(a,b){var A=tokenSet(a),B=tokenSet(b),inter=0,total=0;Object.keys(A).forEach(function(k){total++;if(B[k])inter++;});Object.keys(B).forEach(function(k){if(!A[k])total++;});return total?inter/total:0;}
  function isFundingName(s){s=String(s||'').toLowerCase();return s.indexOf('spending account funding')>=0||s.indexOf('fund living')>=0||s.indexOf('spending acct')>=0;}
  function isSweepName(s){return String(s||'').toLowerCase().indexOf('sweep')>=0;}
  async function fetchMonth(slug){var r=await fetch('/months/'+slug+'.html?v=compare'+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(slug+' HTTP '+r.status);return await r.text();}
  function parseMonth(slug,html){var doc=new DOMParser().parseFromString(html,'text/html');var out=[];doc.querySelectorAll('.day[data-day]').forEach(function(day){var d=Number(day.getAttribute('data-day')||0);day.querySelectorAll('.ev').forEach(function(ev){var cls=ev.className||'';if(cls.indexOf('note')>=0)return;var name=cleanName((ev.querySelector('.nm')||{}).textContent||'');var amt=parseAmount((ev.querySelector('.amt')||{}).textContent||'');if(!name)return;out.push({date:dateKey(slug,d),day:d,name:name,amount:amt,source:'calendar'});});});return out;}
  async function getControl(){var r=await fetch('/api/bills?compare='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('control HTTP '+r.status);return await r.json();}
  function defaultRules(){return {spendingFunding:{enabled:true,amount:1500,count:2,timing:'same-day-income'},sweep:{enabled:true,preferredBuffer:1250,hardBuffer:1000,day:28,label:'Sweep transfer',startingBalance:0}};}
  function mergeRules(r){var d=defaultRules();r=r&&typeof r==='object'?r:{};d.spendingFunding=Object.assign(d.spendingFunding,r.spendingFunding||{});if(d.spendingFunding.timing==='after-income')d.spendingFunding.timing='same-day-income';d.sweep=Object.assign(d.sweep,r.sweep||{});return d;}
  function rulesFromData(data){try{var row=(data.oneTimeEvents||[]).find(function(x){return x.id===RULE_ID;});return mergeRules(row&&row.notes?JSON.parse(row.notes):null);}catch(e){return mergeRules(null);}}
  function datesForOneTime(o,val){var out=[];var text=String(o.notes||'');var matches=text.match(/20\d{2}-\d{2}-\d{2}/g)||[];matches.forEach(function(d){if(d.slice(0,7)===val&&out.indexOf(d)<0)out.push(d);});if(!out.length&&o.date&&o.date.slice(0,7)===val)out.push(o.date);return out;}
  function genIncome(i,dim,push){if(i.active===false)return;var amt=Math.abs(Number(i.amount||0));var name=i.name||'Income';var s=i.schedule||'manual';if(s==='semi-monthly-15-30'){push(15,name,amt);push(Math.min(30,dim),name,amt);}else if(s==='monthly'){push(1,name,amt);}else if(s==='biweekly'){push(1,name,amt);push(15,name,amt);if(dim>=29)push(29,name,amt);}else{push(1,name,amt);}}
  function fundingIncomeDays(rows){var preferred=rows.filter(function(x){var n=String(x.name||'').toLowerCase();return x.amount>0&&(n.indexOf('alissa')>=0||n.indexOf('humc')>=0);}).map(function(x){return x.day;}).sort(function(a,b){return a-b;});if(preferred.length)return preferred;return rows.filter(function(x){return x.amount>0;}).map(function(x){return x.day;}).sort(function(a,b){return a-b;});}
  function generateControlMonth(slug,data){var m=monthNum(slug);var dim=daysInMonth(YEAR,m);var val=YEAR+'-'+String(m).padStart(2,'0');var rows=[];function push(day,name,amount){if(day<1||day>dim)return;rows.push({date:dateKey(slug,day),day:day,name:name,amount:amount,source:'control'});} (data.bills||[]).forEach(function(b){if(b.active===false)return;if(b.frequency&&b.frequency!=='monthly')return;if(b.startMonth&&b.startMonth>val)return;if(b.endMonth&&b.endMonth<val)return;push(Math.min(Number(b.dueDay||1),dim),b.name||'Bill',-Math.abs(Number(b.amount||0)));});(data.oneTimeEvents||[]).forEach(function(o){if(o.id===RULE_ID)return;datesForOneTime(o,val).forEach(function(dt){var d=Number(dt.slice(8,10));var amt=Number(o.amount||0);push(d,o.name||'One-time item',o.type==='income'?Math.abs(amt):-Math.abs(amt));});});(data.income||[]).forEach(function(i){genIncome(i,dim,push);});var rules=rulesFromData(data);var spend=rules.spendingFunding||{};if(spend.enabled!==false&&Number(spend.amount||0)>0&&Number(spend.count||0)>0){var incomeDays=fundingIncomeDays(rows);for(var si=0;si<Number(spend.count||0);si++){var base=spend.timing==='fixed-1-15'?(si===0?1:15):(incomeDays[si]||[1,15,29][si]||1);var add=spend.timing==='day-after-income'?1:0;var sd=Math.min(dim,Math.max(1,base+add));push(sd,'Spending account funding',-Math.abs(Number(spend.amount||0)));}}var sweep=rules.sweep||{};if(sweep.enabled!==false){var income=rows.filter(function(x){return x.amount>0}).reduce(function(s,x){return s+x.amount},0);var outgo=rows.filter(function(x){return x.amount<0}).reduce(function(s,x){return s+Math.abs(x.amount)},0);var available=Number(sweep.startingBalance||0)+income-outgo-Number(sweep.preferredBuffer||0);if(available>0)push(Math.min(dim,Math.max(1,Number(sweep.day||28))),sweep.label||'Sweep transfer',-Math.round(available*100)/100);}return rows;}
  function compareRows(calendar,control){var diffs=[],matchedC={},matchedP={};function mark(ci,pi){matchedC[ci]=1;matchedP[pi]=1;}calendar.forEach(function(c,ci){for(var pi=0;pi<control.length;pi++){if(matchedP[pi])continue;var p=control[pi];if(normKey(c)===normKey(p)){mark(ci,pi);if(!sameAmount(c,p))diffs.push({type:'Amount mismatch',date:c.date,name:c.name,previewName:p.name,calendar:c.amount,control:p.amount});return;}}});calendar.forEach(function(c,ci){if(matchedC[ci])return;for(var pi=0;pi<control.length;pi++){if(matchedP[pi])continue;var p=control[pi];if(c.date===p.date&&sameAmount(c,p)){mark(ci,pi);diffs.push({type:'Likely rename only',date:c.date,name:c.name,previewName:p.name,calendar:c.amount,control:p.amount});return;}}});calendar.forEach(function(c,ci){if(matchedC[ci])return;var best=-1,bestScore=0;for(var pi=0;pi<control.length;pi++){if(matchedP[pi])continue;var p=control[pi];if(!sameAmount(c,p))continue;var dayGap=Math.abs(c.day-p.day);var score=nameScore(c.name,p.name)-(dayGap*.08);if(score>bestScore){bestScore=score;best=pi;}}if(best>=0&&bestScore>=.2){var p=control[best];mark(ci,best);diffs.push({type:'Likely rename/date shift',date:c.date,name:c.name,previewName:p.name+' on '+p.date,calendar:c.amount,control:p.amount});}});calendar.forEach(function(c,ci){if(!matchedC[ci])diffs.push({type:(isFundingName(c.name)||isSweepName(c.name))?'System-rule missing':'Missing from preview',date:c.date,name:c.name,previewName:'',calendar:c.amount,control:null});});control.forEach(function(p,pi){if(!matchedP[pi])diffs.push({type:(isFundingName(p.name)||isSweepName(p.name))?'System-rule extra':'Extra in preview',date:p.date,name:'',previewName:p.name,calendar:null,control:p.amount});});return diffs.sort(function(a,b){return a.date.localeCompare(b.date)||a.type.localeCompare(b.type);});}
  function addTab(){if(document.querySelector('[data-tab="compare"]'))return;var tabs=document.querySelector('.tabs');if(!tabs)return;var backup=document.querySelector('[data-tab="backup"]');var btn=document.createElement('button');btn.className='tab';btn.dataset.tab='compare';btn.textContent='Compare Mode';btn.onclick=function(){showTab('compare');};tabs.insertBefore(btn,backup||null);var panel=document.createElement('section');panel.id='panel-compare';panel.className='panel';panel.innerHTML='<div class="card"><div class="cardhead"><div><h2>Compare Mode</h2><p class="mut" style="margin:4px 0 0">Compares the existing dashboard calendar against the Control Center generated preview. Spending funding now prefers Alissa / HUMC income dates.</p></div><button class="btn small" onclick="runCompareMode()">Run compare</button></div><div class="grid"><div class="field"><label>Month</label><select id="compareMonth"><option value="july">July</option><option value="aug">August</option><option value="sep">September</option><option value="oct">October</option><option value="nov">November</option><option value="dec">December</option><option value="june">June</option></select></div></div><div id="compareStatus" class="status">Ready.</div><div id="compareOutput"></div></div>';tabs.parentNode.insertBefore(panel,document.getElementById('panel-backup'));}
  function setStatus(t,k){var el=document.getElementById('compareStatus');if(el){el.textContent=t;el.className='status '+(k||'');}}
  window.runCompareMode=async function(){try{var slug=(document.getElementById('compareMonth')||{}).value||'july';setStatus('Comparing '+monthName(slug)+'…','warn');var html=await fetchMonth(slug);var calendar=parseMonth(slug,html);var data=await getControl();var control=generateControlMonth(slug,data);var diffs=compareRows(calendar,control);var system=diffs.filter(function(d){return d.type.indexOf('System-rule')===0;});var material=diffs.filter(function(d){return d.type.indexOf('Likely rename')!==0&&d.type.indexOf('System-rule')!==0;});var out=document.getElementById('compareOutput');var calIn=calendar.filter(function(x){return x.amount>0}).reduce(function(s,x){return s+x.amount},0), calOut=calendar.filter(function(x){return x.amount<0}).reduce(function(s,x){return s+Math.abs(x.amount)},0);var conIn=control.filter(function(x){return x.amount>0}).reduce(function(s,x){return s+x.amount},0), conOut=control.filter(function(x){return x.amount<0}).reduce(function(s,x){return s+Math.abs(x.amount)},0);var htmlOut='<div class="preview-summary"><div class="preview-kpi"><span>Calendar items</span><b>'+calendar.length+'</b></div><div class="preview-kpi"><span>Preview items</span><b>'+control.length+'</b></div><div class="preview-kpi"><span>Material differences</span><b>'+material.length+'</b></div><div class="preview-kpi"><span>System-rule differences</span><b>'+system.length+'</b></div></div>';if(!diffs.length){htmlOut+='<div class="empty">No line-level differences found for '+esc(monthName(slug))+'.</div>';}else{htmlOut+='<div class="tablewrap"><table><thead><tr><th>Type</th><th>Date</th><th>Dashboard name</th><th>Preview name</th><th>Dashboard</th><th>Preview</th></tr></thead><tbody>'+diffs.map(function(d){return '<tr><td>'+esc(d.type)+'</td><td>'+esc(d.date)+'</td><td><b>'+esc(d.name||'')+'</b></td><td><b>'+esc(d.previewName||'')+'</b></td><td>'+money(Math.abs(d.calendar||0))+'</td><td>'+money(Math.abs(d.control||0))+'</td></tr>';}).join('')+'</tbody></table></div><div class="preview-note">Net delta: '+money((conIn-conOut)-(calIn-calOut))+'</div>';}out.innerHTML=htmlOut;setStatus('Compare complete · '+material.length+' material differences, '+system.length+' system-rule differences.','ok');}catch(e){setStatus('Compare failed: '+e.message,'warn');}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addTab);else addTab();
})();
