(function(){
  var RULE_ID='__billsos_system_rules__';
  var DEFAULT_RULES={spendingFunding:{enabled:true,amount:1500,count:2,timing:'same-day-income'},sweep:{enabled:true,preferredBuffer:1250,hardBuffer:1000,day:28,label:'Sweep transfer',startingBalance:0}};
  function esc(s){return String(s||'').replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
  function clone(o){return JSON.parse(JSON.stringify(o));}
  function mergeRules(r){var d=clone(DEFAULT_RULES);r=r&&typeof r==='object'?r:{};d.spendingFunding=Object.assign(d.spendingFunding,r.spendingFunding||{});if(d.spendingFunding.timing==='after-income')d.spendingFunding.timing='same-day-income';d.sweep=Object.assign(d.sweep,r.sweep||{});return d;}
  function findRuleRow(data){return (data.oneTimeEvents||[]).find(function(x){return x&&x.id===RULE_ID;});}
  function rulesFromData(data){try{var row=findRuleRow(data);return mergeRules(row&&row.notes?JSON.parse(row.notes):null);}catch(e){return mergeRules(null);}}
  function putRulesIntoData(data,rules){data.oneTimeEvents=Array.isArray(data.oneTimeEvents)?data.oneTimeEvents:[];var clean=data.oneTimeEvents.filter(function(x){return x.id!==RULE_ID;});clean.push({id:RULE_ID,name:'BillsOS system rules',date:'2099-12-31',amount:0,type:'transfer',notes:JSON.stringify(mergeRules(rules))});data.oneTimeEvents=clean;return data;}
  async function loadAll(){var r=await fetch('/api/bills?rules='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}
  async function saveAll(data){var r=await fetch('/api/bills',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}
  function setRulesStatus(t,k){var el=document.getElementById('rulesStatus');if(el){el.textContent=t;el.className='status '+(k||'');}}
  function addTab(){
    if(document.querySelector('[data-tab="rules"]'))return;
    var tabs=document.querySelector('.tabs');
    if(!tabs)return;
    var backup=document.querySelector('[data-tab="backup"]');
    var btn=document.createElement('button');btn.className='tab';btn.dataset.tab='rules';btn.textContent='Rules';btn.onclick=function(){showTab('rules');loadRulesForm();};
    tabs.insertBefore(btn,backup||null);
    var panel=document.createElement('section');panel.id='panel-rules';panel.className='panel';
    panel.innerHTML='<div class="card"><div class="cardhead"><div><h2>Generated transfer rules</h2><p class="mut" style="margin:4px 0 0">BillsOS will generate these items automatically in Preview Calendar. You should not have to enter each date manually.</p></div><button class="btn small" onclick="loadRulesForm()">Refresh rules</button></div><div id="rulesStatus" class="status">Loading rules…</div><div class="grid" style="margin-top:12px"><div class="field"><label>Spending funding on/off</label><select id="ruleSpendEnabled"><option value="true">Enabled</option><option value="false">Disabled</option></select></div><div class="field small"><label>Funding amount</label><input id="ruleSpendAmount" type="number" step="0.01"></div><div class="field small"><label>Times per month</label><input id="ruleSpendCount" type="number" min="0" max="4"></div><div class="field"><label>Timing</label><select id="ruleSpendTiming"><option value="same-day-income">Same day as income</option><option value="day-after-income">Day after income</option><option value="fixed-1-15">Fixed 1st and 15th</option></select></div><div class="field"><label>Sweep on/off</label><select id="ruleSweepEnabled"><option value="true">Enabled</option><option value="false">Disabled</option></select></div><div class="field small"><label>Preferred buffer</label><input id="rulePreferredBuffer" type="number" step="0.01"></div><div class="field small"><label>Hard minimum</label><input id="ruleHardBuffer" type="number" step="0.01"></div><div class="field small"><label>Sweep day</label><input id="ruleSweepDay" type="number" min="1" max="31"></div><div class="field small"><label>Month start balance</label><input id="ruleStartingBalance" type="number" step="0.01"></div><div class="field wide"><label>Sweep label</label><input id="ruleSweepLabel"></div></div><div class="actions"><button class="btn primary" onclick="saveRulesForm()">Save rules</button></div></div><div class="card"><h2>What BillsOS generates</h2><p class="mut">Spending funding creates the planned spending account transfers. Sweep calculates leftover cash above the preferred buffer after generated activity. These show in Preview Calendar as system-generated items.</p></div>';
    tabs.parentNode.insertBefore(panel,document.getElementById('panel-backup'));
  }
  window.loadRulesForm=async function(){try{setRulesStatus('Loading rules…','warn');var data=await loadAll();var rules=rulesFromData(data);document.getElementById('ruleSpendEnabled').value=String(rules.spendingFunding.enabled!==false);document.getElementById('ruleSpendAmount').value=rules.spendingFunding.amount||1500;document.getElementById('ruleSpendCount').value=rules.spendingFunding.count||2;document.getElementById('ruleSpendTiming').value=rules.spendingFunding.timing||'same-day-income';document.getElementById('ruleSweepEnabled').value=String(rules.sweep.enabled!==false);document.getElementById('rulePreferredBuffer').value=rules.sweep.preferredBuffer||1250;document.getElementById('ruleHardBuffer').value=rules.sweep.hardBuffer||1000;document.getElementById('ruleSweepDay').value=rules.sweep.day||28;document.getElementById('ruleStartingBalance').value=rules.sweep.startingBalance||0;document.getElementById('ruleSweepLabel').value=rules.sweep.label||'Sweep transfer';setRulesStatus('Rules loaded','ok');}catch(e){setRulesStatus('Could not load rules.','warn');}};
  window.saveRulesForm=async function(){try{setRulesStatus('Saving rules…','warn');var data=await loadAll();var rules={spendingFunding:{enabled:document.getElementById('ruleSpendEnabled').value==='true',amount:Number(document.getElementById('ruleSpendAmount').value||0),count:Number(document.getElementById('ruleSpendCount').value||0),timing:document.getElementById('ruleSpendTiming').value},sweep:{enabled:document.getElementById('ruleSweepEnabled').value==='true',preferredBuffer:Number(document.getElementById('rulePreferredBuffer').value||0),hardBuffer:Number(document.getElementById('ruleHardBuffer').value||0),day:Number(document.getElementById('ruleSweepDay').value||28),startingBalance:Number(document.getElementById('ruleStartingBalance').value||0),label:document.getElementById('ruleSweepLabel').value||'Sweep transfer'}};await saveAll(putRulesIntoData(data,rules));setRulesStatus('Rules saved. Open Preview Calendar and refresh preview.','ok');if(typeof loadData==='function')loadData();}catch(e){setRulesStatus('Rules save failed.','warn');}};
  function hideRuleRows(){document.querySelectorAll('td b').forEach(function(b){if(b.textContent==='BillsOS system rules'){var tr=b.closest('tr');if(tr)tr.style.display='none';}});}
  var oldRenderOne=window.renderOne;if(typeof oldRenderOne==='function')window.renderOne=function(){oldRenderOne();setTimeout(hideRuleRows,0);};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addTab);else addTab();
})();
