(function(){
  var MONTHS=['june','july','aug','sep','oct','nov','dec'];
  var YEAR=2026;
  var imported=[];
  function esc(s){return String(s||'').replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
  function money(v){var n=Number(v||0);return n?n.toLocaleString(undefined,{style:'currency',currency:'USD'}):'$0.00'}
  function monthNum(slug){return {june:6,july:7,aug:8,sep:9,oct:10,nov:11,dec:12}[slug]||1;}
  function dateKey(slug,day){return YEAR+'-'+String(monthNum(slug)).padStart(2,'0')+'-'+String(day).padStart(2,'0')}
  function parseAmount(s){s=String(s||'').replace(/[,$\s]/g,'').replace(/[−–—]/g,'-'); if(!s)return 0; return Number(s)||0;}
  function cleanName(s){return String(s||'').replace(/\s+/g,' ').replace(/\s*✓\s*$/,'').trim();}
  function normalizeName(s){return cleanName(s).replace(/\*$/,'').replace(/—.*/,'').replace(/-.*/,'').replace(/\s+/g,' ').trim();}
  function category(name,cls,amt){var n=name.toLowerCase(); if(cls.indexOf('in')>=0||amt>0||n.includes('paycheck')||n.includes('humc')||n.includes('unilever'))return 'income'; if(n.includes('fund living')||n.includes('spending acct')||n.includes('spending account'))return 'system-rule'; if(n.includes('sweep'))return 'system-rule'; if(cls.indexOf('xfer')>=0||n.includes('transfer'))return 'transfer'; return 'bill';}
  async function fetchMonth(slug){var r=await fetch('/months/'+slug+'.html?v=import'+Date.now(),{cache:'no-store'}); if(!r.ok)throw new Error(slug+' HTTP '+r.status); return await r.text();}
  function parseMonth(slug,html){var doc=new DOMParser().parseFromString(html,'text/html'); var rows=[]; doc.querySelectorAll('.day[data-day]').forEach(function(day){var d=Number(day.getAttribute('data-day')||0); day.querySelectorAll('.ev').forEach(function(ev){var name=cleanName((ev.querySelector('.nm')||{}).textContent||''); var amt=parseAmount((ev.querySelector('.amt')||{}).textContent||''); var cls=ev.className||''; if(!name||cls.indexOf('note')>=0)return; rows.push({month:slug,date:dateKey(slug,d),day:d,name:name,baseName:normalizeName(name),amount:amt,kind:category(name,cls,amt),className:cls,source:'calendar'});});}); return rows;}
  function groupRows(rows){var groups={}; rows.forEach(function(r){var key=r.kind+'|'+r.baseName+'|'+Math.abs(r.amount).toFixed(2); (groups[key]||(groups[key]=[])).push(r);}); return Object.keys(groups).map(function(k){var g=groups[k]; var first=g[0]; var days=g.map(x=>x.day); var sameDay=days.every(d=>d===days[0]); var recurring=g.length>=2&&sameDay&&(first.kind==='bill'||first.kind==='income'||first.kind==='transfer'); var bucket=first.kind==='system-rule'?'System rule':(recurring?'Recurring '+first.kind:(first.kind==='income'?'Income one-time':'One-time / review')); return {key:k,bucket:bucket,name:first.baseName||first.name,amount:Math.abs(first.amount),signedAmount:first.amount,kind:first.kind,dueDay:sameDay?days[0]:null,count:g.length,months:g.map(x=>x.month).join(', '),dates:g.map(x=>x.date).join(', '),rows:g,selected:first.kind!=='system-rule'};}).sort(function(a,b){return a.bucket.localeCompare(b.bucket)||a.name.localeCompare(b.name);});}
  function addTab(){if(document.querySelector('[data-tab="import"]'))return; var tabs=document.querySelector('.tabs'); if(!tabs)return; var backup=document.querySelector('[data-tab="backup"]'); var btn=document.createElement('button'); btn.className='tab'; btn.dataset.tab='import'; btn.textContent='Import Calendar'; btn.onclick=function(){showTab('import');}; tabs.insertBefore(btn,backup||null); var panel=document.createElement('section'); panel.id='panel-import'; panel.className='panel'; panel.innerHTML='<div class="card"><div class="cardhead"><div><h2>Import existing calendar</h2><p class="mut" style="margin:4px 0 0">Scans the current calendar month files and proposes Control Center rows. It will not change the dashboard.</p></div><button class="btn small" onclick="scanCalendarImport()">Scan existing calendar</button></div><div id="importStatus" class="status">Ready to scan.</div><div id="importOutput"></div></div>'; tabs.parentNode.insertBefore(panel,document.getElementById('panel-backup'));}
  function setStatus(t,k){var el=document.getElementById('importStatus'); if(el){el.textContent=t; el.className='status '+(k||'');}}
  function renderImport(groups){imported=groups; var out=document.getElementById('importOutput'); if(!out)return; var counts=groups.reduce(function(a,g){a[g.bucket]=(a[g.bucket]||0)+1;return a;},{}); var html='<div class="preview-summary"><div class="preview-kpi"><span>Groups found</span><b>'+groups.length+'</b></div><div class="preview-kpi"><span>Recurring bills</span><b>'+(counts['Recurring bill']||0)+'</b></div><div class="preview-kpi"><span>Income</span><b>'+((counts['Recurring income']||0)+(counts['Income one-time']||0))+'</b></div><div class="preview-kpi"><span>Needs review</span><b>'+(counts['One-time / review']||0)+'</b></div></div>'; html+='<div class="actions"><button class="btn primary" onclick="saveSelectedImport()">Save selected rows to Control Center</button></div>'; html+='<div class="tablewrap" style="margin-top:12px"><table><thead><tr><th>Import?</th><th>Bucket</th><th>Name</th><th>Amount</th><th>Due/day</th><th>Seen</th><th>Dates</th></tr></thead><tbody>'+groups.map(function(g,i){return '<tr><td><input type="checkbox" data-import-i="'+i+'" '+(g.selected?'checked':'')+'></td><td>'+esc(g.bucket)+'</td><td><b>'+esc(g.name)+'</b></td><td>'+money(g.amount)+'</td><td>'+esc(g.dueDay||'varies')+'</td><td>'+g.count+'</td><td class="mut">'+esc(g.dates)+'</td></tr>';}).join('')+'</tbody></table></div>'; out.innerHTML=html;}
  window.scanCalendarImport=async function(){try{setStatus('Scanning existing calendar…','warn'); var all=[]; for(var i=0;i<MONTHS.length;i++){var html=await fetchMonth(MONTHS[i]); all=all.concat(parseMonth(MONTHS[i],html));} var groups=groupRows(all); renderImport(groups); setStatus('Scan complete · '+all.length+' calendar events grouped into '+groups.length+' proposed rows.','ok');}catch(e){setStatus('Scan failed: '+e.message,'warn');}};
  function rowToControl(g){if(g.kind==='income'&&g.bucket.indexOf('Recurring')===0){return {target:'income',row:{id:'import-income-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),name:g.name,amount:g.amount,schedule:'manual',active:true,notes:'Imported from existing calendar. Review schedule.'}};} if(g.kind==='bill'&&g.bucket.indexOf('Recurring')===0){return {target:'bills',row:{id:'import-bill-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),name:g.name,amount:g.amount,dueDay:g.dueDay||1,type:'bill',frequency:'monthly',startMonth:null,endMonth:null,active:true,notes:'Imported from existing calendar.'}};} return {target:'oneTimeEvents',row:{id:'import-one-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),name:g.name,date:g.rows[0].date,amount:g.amount,type:g.kind==='income'?'income':(g.kind==='transfer'?'transfer':'bill'),notes:'Imported from existing calendar. Dates seen: '+g.dates}};}
  window.saveSelectedImport=async function(){try{var picks=[]; document.querySelectorAll('[data-import-i]:checked').forEach(function(box){picks.push(imported[Number(box.getAttribute('data-import-i'))]);}); if(!picks.length){setStatus('Nothing selected.','warn');return;} setStatus('Saving selected import rows…','warn'); var r=await fetch('/api/bills?import='+Date.now(),{cache:'no-store'}); if(!r.ok)throw new Error('HTTP '+r.status); var data=await r.json(); data.bills=Array.isArray(data.bills)?data.bills:[]; data.oneTimeEvents=Array.isArray(data.oneTimeEvents)?data.oneTimeEvents:[]; data.income=Array.isArray(data.income)?data.income:[]; picks.forEach(function(g){var converted=rowToControl(g); data[converted.target].push(converted.row);}); var wr=await fetch('/api/bills',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); if(!wr.ok)throw new Error('Save HTTP '+wr.status); setStatus('Imported '+picks.length+' selected rows. Refresh the Bills/Income/One-time tabs to review.','ok'); if(typeof loadData==='function')loadData();}catch(e){setStatus('Import save failed: '+e.message,'warn');}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addTab);else addTab();
})();
