(function(){
  'use strict';
  var BUILD='dashboard-sync-20260629-1';
  var keys=['billsos-one-time-bills-v1','billsos-one-time-bills','billsos-manual-bills-v1','billsos-assistant-bills-v1','billsos-payment-log-v1','billsos-activity-log-v1'];
  window.BillsOSModules=window.BillsOSModules||{};
  function text(v){return String(v||'').replace(/\s+/g,' ').trim();}
  function dateOf(v){var m=String(v||'').match(/20\d{2}-\d{2}-\d{2}/);return m?m[0]:'';}
  function amountOf(v){var n=Number(String(v||'').replace(/−/g,'-').replace(/[^0-9.\-]/g,''));return isNaN(n)?0:Math.abs(n);}
  function moneyOut(n){return '−'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});}
  function monthId(n){return ['june','july','aug','sep','oct','nov','dec'][n-6]||'';}
  function collect(value,out){if(!value)return;if(Array.isArray(value)){value.forEach(function(x){collect(x,out);});return;}if(typeof value==='object'){var d=dateOf(value.iso||value.date||value.dueDate||value.due||value.when);var a=amountOf(value.amount||value.value||value.payment||value.total);var name=text(value.name||value.title||value.bill||value.payee||value.merchant||value.description||value.memo);if(d&&a&&name)out.push({date:d,amount:a,name:name});['items','bills','payments'].forEach(function(k){if(value[k])collect(value[k],out);});}}
  function savedBills(){var list=[];keys.forEach(function(k){try{collect(JSON.parse(localStorage.getItem(k)||'null'),list);}catch(e){}});var seen={};return list.filter(function(x){var id=x.date+'|'+x.amount+'|'+x.name;if(seen[id])return false;seen[id]=1;return true;});}
  function inject(){var changed=false;savedBills().forEach(function(x){var p=x.date.split('-'),panel=document.getElementById('panel-'+monthId(Number(p[1]))),day=panel&&panel.querySelector('.day[data-day="'+Number(p[2])+'"]');if(!day)return;var events=day.querySelector('.events');if(!events){events=document.createElement('div');events.className='events';day.appendChild(events);}var id=x.name+'|'+moneyOut(x.amount);var exists=[].slice.call(events.querySelectorAll('.ev')).some(function(ev){return text((ev.querySelector('.nm')||{}).textContent)+'|'+text((ev.querySelector('.amt')||{}).textContent)===id;});if(exists)return;var ev=document.createElement('div');ev.className='ev out billsos-one-time';ev.innerHTML='<span class="dot"></span><span class="nm"></span><span class="flag manual">M</span><span class="amt"></span>';ev.querySelector('.nm').textContent=x.name;ev.querySelector('.amt').textContent=moneyOut(x.amount);events.appendChild(ev);changed=true;});if(changed)updateOpenCount();}
  function updateOpenCount(){var items=[].slice.call(document.querySelectorAll('.day[data-day] .ev')).filter(function(ev){return !ev.classList.contains('in')&&!ev.classList.contains('note')&&!ev.classList.contains('done');});var el=document.getElementById('heroNextActions');if(el)el.textContent=String(items.length);var note=document.getElementById('heroNextActionsNote');if(note&&items[0])note.textContent='Next: '+text((items[0].querySelector('.nm')||{}).textContent);}
  function init(){try{inject();var target=document.getElementById('month-panels')||document.body;new MutationObserver(inject).observe(target,{childList:true,subtree:true});window.addEventListener('storage',inject);setInterval(inject,2000);window.BillsOSModules.dashboardSync={loaded:true,build:BUILD,at:new Date().toISOString()};}catch(e){window.BillsOSModules.dashboardSync={loaded:false,error:String(e&&e.message||e),build:BUILD};}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
